### ISSUE TITLE
Custom Fonts Crash Google Chrome

### ISSUE THREAD

**Issue by dtinth** [dtinth/YosemiteSystemFontPatcher#11]
Problem
------------

When the font replacement is installed, Google Chrome crashes instantly. This only happens on some machines and some fonts.

Related Issues
--------------------

| Issue Reference | Reporter |
| ---------------------- | ------------ |
| #10 | @kemie |
| #3 (Comment № 4) | @vistamin |
| seanmpuckett/Myriad-Pro-System-Font-for-Yosemite#1 | @vincfleurette |
| kemie/Source-Sans-Yosemite-System-Font-Replacement#1 | @hex |

Current Status: Community Help Wanted
--------------------

- The `patch` script has been updated to change the SFNT table to a unique name. When non-unique name is used, it confuses some applications.
   - Although this fixes the issue where the wrong font is used, Chrome still crashes.
   - Since I don't know of any other potential fixes yet, this issue remains open. Any help or pull requests are much appreciated.

**Comment by bcse** [comment]
d9b7bba2239ea29903cb631bb7ed892071d1f52c fixed this issue for me.
In my test, Chrome doesn't like font family name begin with a decimal dot (this means that such PostScript name is hidden).

**Comment by chrisjrn** [comment]
This is definitely working for me.

**Comment by dtinth** [comment]
Wow. So I fixed it by chance. I'll close this then.
