### ISSUE TITLE
Cannot Install Fontforge + Python Scripting Support 

### ISSUE THREAD

**Issue by mbspb** [dtinth/YosemiteSystemFontPatcher#13]
Hello fine sir, 

I'm on the latest Yosemite beta (10.10.2) and I can't get the script to run properly. I've installed Homebrew, the latest version of Python, XQuartz, and even installed FontForge separately from it's git, but I still can't get the script to run. 

When I attempt to run:

"brew install fontforge --with-python"

it spits out that my c compiler cannot create executables:

![screen shot 2014-11-21 at 12 03 01 pm](https://cloud.githubusercontent.com/assets/9886373/5146136/31edf4c2-7177-11e4-8a24-d27b6847ef25.png)

If I try running the Font Patcher script even after that compiler error, it just gives me an error saying that FontForge with Python scripting support is not installed properly: (Which I'm guessing it's not.)

![screen shot 2014-11-21 at 12 03 46 pm](https://cloud.githubusercontent.com/assets/9886373/5146171/93ead2ee-7177-11e4-8937-760023769b16.png)

I'm rather new to all this, but I'd really like to change my system font to Avenir Next, so if you could help me figure out what's wrong that would be supremely appreciated
.
Cheers,
~Mike

**Comment by sulaiman7** [comment]
*Reopening case* @mbspb Can you share me your *Avenir Next* font, please? I'm unable to move forward after following the above solution. It failed many times and receiving the errors repeatedly.

Thank you!
