### ISSUE TITLE
Dialogs have missing fonts

### ISSUE THREAD

**Issue by ghost** [dtinth/YosemiteSystemFontPatcher#16]
Not sure if it's a font issue but I used a legit version of Avenir Next and everything works smoothly apart from login dialogs..

![screen shot 2014-12-25 at 8 54 58 pm](https://cloud.githubusercontent.com/assets/1431990/5553539/69c0bdb4-8c78-11e4-9d01-7bfac66b20cd.png)

Any ideas?

**Comment by HeikoKanzlerNektan** [comment]
Thanks, that did it for me. For some reason, I had the fonts in my user folder as well.

**Comment by dtinth** [comment]
I thought that the reason is that because the instructions in the README.md said that you put in the user folder. I'll fix that. Thanks.

So I guess this is solved.

**Comment by Laney23** [comment]
I'm having issues installing this on Capitan. Every time I try to run the binary, it tells me that FontForge is not installed properly
